# Generated by Django 4.1.6 on 2023-02-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(max_length=255, verbose_name='Weather Station')),
                ('date', models.DateField(max_length=50, verbose_name='Reported Date(YYYYMMDD)')),
                ('temp_high', models.FloatField(default=None, help_text='The maximum temperature for that day (in tenths of a degree Celsius)', verbose_name='Temperature Maximum')),
                ('temp_low', models.FloatField(default=None, help_text='The Minimum temperature for that day (in tenths of a degree Celsius)', verbose_name='Temperature Minimum')),
                ('precip', models.FloatField(default=None, help_text='The amount of precipitation for that day (in tenths of a millimeter)', verbose_name='Precipitation')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDataStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_station', models.CharField(max_length=255, verbose_name='Weather Station')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('avg_temp_high', models.FloatField(default=None, verbose_name='Avg High Temperature')),
                ('avg_temp_low', models.FloatField(default=None, verbose_name='Avg Low Temperature')),
                ('total_precip', models.FloatField(default=None, verbose_name='Total Precipitation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='weatherdata',
            constraint=models.UniqueConstraint(fields=('weather_station', 'date', 'temp_high', 'temp_low', 'precip'), name='unique weather data'),
        ),
    ]
